name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: prod
        url: 'https://wallin.design'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Set up dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Caching
      - name: Cache Pulumi plugins
        uses: actions/cache@v4
        with:
          path: ~/.pulumi/plugins
          key: ${{ runner.os }}-pulumi-deploy-${{ hashFiles('deploy/go.mod', 'deploy/Pulumi.*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pulumi-deploy-
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          # Could be optimized to a more granular level
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Setup
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      # Prepare the environment
      - name: Install site dependencies
        run: npm ci --include=dev
      - name: Install deploy dependencies
        working-directory: deploy
        run: npm ci --include=dev
      - name: Build site
        run: npm run build

      # Deploy
      - name: Deploy
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: sidus/felicia-portfolio/prod
          work-dir: deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
